apiVersion: v2
name: main
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: clusterd
    version: 0.1.0
    repository: "file://../clusterd"
  - name: dlpd
    version: 0.1.0
    repository: "file://../dlpd"
  - name: rated
    version: 0.1.0
    repository: "file://../rated"
  - name: sasid
    version: 0.1.0
    repository: "file://../sasid"
  - name: savdid
    version: 0.1.0
    repository: "file://../savdid"
  - name: expurgate
    version: 0.1.0
    repository: "file://../expurgate"
  - name: smtpd
    version: 0.1.0
    repository: "file://../smtpd"
  - name: web
    version: 0.1.0
    repository: "file://../web"
