# These are the global settings that must be accessible fom all charts
global:
  smtpd:
    enabled: true
    service:
      type: ClusterIP
      port: 25
    api:
      service:
        type: ClusterIP
        port: 80
    prometheus:
      # The "halon-extras-prometheus" package needs to be installed in the "smtpd" container if you want to enable this
      enabled: false
      port: 9100
      # If a "PodMonitor" should be automatically created. This requires that the "Prometheus Operator" is installed in Kubernetes
      monitor: false 
  clusterd:
    enabled: true
    service:
      type: ClusterIP
      port: 2530
  web:
    enabled: true
    service:
      type: ClusterIP
      port: 80
  classifier:
    enabled: false
    service:
      type: ClusterIP
      port: 8000
  dlpd:
    # The "halon-extras-dlp" package needs to be installed in the "smtpd" container if you want to enable this
    enabled: false
    service:
      type: ClusterIP
      port: 3000
  rated:
    # The "halon-extras-rate" package needs to be installed in the "smtpd" container if you want to enable this
    enabled: false
    service:
      type: ClusterIP
      port: 3000
    api:
      service:
        type: ClusterIP
        port: 80
  sasid:
    # The "halon-extras-sophos" package needs to be installed in the "smtpd" container if you want to enable this
    enabled: false
    service:
      type: ClusterIP
      port: 25315
  savdid:
    # The "halon-extras-sophos" package needs to be installed in the "smtpd" container if you want to enable this
    enabled: false
    service:
      type: ClusterIP
      port: 4010
  expurgate:
    # The "halon-extras-eleven" package needs to be installed in the "smtpd" container if you want to enable this
    enabled: false
    service:
      type: ClusterIP
      port: 783

# These are the per-chart settings that do not need to be accessible from all other charts
smtpd:
  replicaCount: 2
  storage: 10Gi
  storageClassName: standard
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  # api:
  #   resources:
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
clusterd: {}
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
web:
  users:
    - username: admin
      password: $2y$12$BzWuHfwX9qDhhomp4Oe/5.7FYwrk1sQfytTeoosv7tqXv/D8hOebO
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
classifier:
  replicaCount: 2
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
dlpd:
  replicaCount: 2
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
rated:
  replicaCount: 2
  clusterSyncKey: a3f5d2817bfc9247adceb8362d4eac5c3798d42e
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
  # api:
  #   resources:
  #     limits:
  #       cpu: 100m
  #       memory: 128Mi
  #     requests:
  #       cpu: 100m
  #       memory: 128Mi
sasid:
  replicaCount: 2
  env:
    - name: SASI_USER
      value: "username"
    - name: SASI_PASSWORD
      value: "password"
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
savdid:
  replicaCount: 2
  storage: 1Gi
  storageClassName: standard
  updateURL: https://sophos.halon.io/1/XXXXXXXXXX
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
expurgate:
  replicaCount: 2
  # resources:
  #   limits:
  #     cpu: 100m
  #     memory: 128Mi
  #   requests:
  #     cpu: 100m
  #     memory: 128Mi
