apiVersion: v1
kind: ConfigMap
metadata:
  name: dlpd
  namespace: halon
data:
  dlpctl.yaml: |-
    version: "6.4"
    environment:
      controlsocket:
        port: 5003
  dlpd-app.yaml: |-
    version: "6.4"
    rules: []
  dlpd.yaml: |
    version: "6.4"
    environment:
      controlsocket:
        port: 5003
      socket:
        port: 5004
      privdrop:
        user: dlpd
        group: dlpd
      umask: "0027"
---
apiVersion: v1
kind: Service
metadata:
  name: dlpd
  namespace: halon
  labels:
    app: dlpd
spec:
  ports:
  - port: 5004
    name: socket
  selector:
    app: dlpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlpd
  namespace: halon
  labels:
    app: dlpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dlpd
  template:
    metadata:
      labels:
        app: dlpd
    spec:
      containers:
      - name: dlpd
        image: halon/dlpd:6.4.0
        ports:
        - containerPort: 5003
          name: controlsocket
        - containerPort: 5004
          name: socket
        readinessProbe:
          tcpSocket:
            port: 5004
        volumeMounts:
        - mountPath: /etc/halon
          name: config
      volumes:
      - name: config
        configMap:
          name: dlpd