{{- if .Values.global.savdid.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "savdid.fullname" . }}
  labels:
    {{- include "savdid.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
        storage: {{ .Values.storage }}
{{- end }}