{{- if .Values.global.savdid.enabled -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "savdid.serviceAccountName" . }}
  labels:
    {{- include "savdid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "savdid.fullname" . }}
  labels:
    {{- include "savdid.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - {{ include "savdid.fullname" . }}
    verbs:
      - get
      - update
      - patch
{{- end }}
---
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "savdid.fullname" . }}
  labels:
    {{- include "savdid.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "savdid.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "savdid.serviceAccountName" . }}
{{- end }}
{{- end }}