{{- if .Values.global.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.web.service.type }}
  ports:
    - port: {{ .Values.global.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
{{- end }}