apiVersion: v1
kind: ConfigMap
metadata:
  name: smtpd
  namespace: halon
data:
  smtpd-app.yaml: |
    version: "6.3"
    servers:
      - id: default
        transport: mx
    transportgroups:
      - id: default
        retry:
          count: 30
          intervals:
            - interval: 60
            - interval: 900
            - interval: 3600
              notify: true
            - interval: 7200
            - interval: 10800
        dsn:
          transport: mx
        transports:
          - id: mx
            session:
              tls:
                mode: dane
    resolver:
      cache:
        size: 10000
    plugins:
      - id: rate
        config:
          port: 5002
          address: rated.halon.svc.cluster.local
      - id: dlp
        config:
          port: 5004
          address: dlpd.halon.svc.cluster.local
  smtpd.yaml: |
    version: "6.3"
    servers:
      - id: default
        listeners:
          - port: 25
    plugins:
      - id: rate
        config:
          reresolve: 5
    environment:
      uuid:
        version: 4
      controlsocket:
        port: 5000
      privdrop:
        user: smtpd
        group: smtpd
      umask: "0027"
      rlimit:
        nofile: 70000
      licensekey: /license.key
  api.yaml: |
    version: "6.3"
    listeners:
      - port: 80
    environment:
      privdrop:
        user: api
        group: api
      controlsockets:
        smtpd:
          port: 5000
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: spool
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spool-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: spool
  local:
    path: /spool-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spool-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: spool
  local:
    path: /spool-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spool-3
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: spool
  local:
    path: /spool-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop
---
apiVersion: v1
kind: Service
metadata:
  name: smtpd
  namespace: halon
  labels:
    app: smtpd
spec:
  ports:
  - port: 25
    name: smtp
  - port: 80
    name: api
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    app: smtpd
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: smtpd
  namespace: halon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smtpd
  template:
    metadata:
      labels:
        app: smtpd
    spec:
      terminationGracePeriodSeconds: 3600
      containers:
      - name: smtpd
        image: smtpd:6.3.1
        ports:
        - containerPort: 5000
          name: controlsocket
        - containerPort: 25
          name: smtp
        readinessProbe:
          tcpSocket:
            port: 25
        volumeMounts:
        - name: spool
          mountPath: /var/spool/halon/queue
        - mountPath: /etc/halon
          name: config
      - name: api
        image: api:6.3.1
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          tcpSocket:
            port: 80
        volumeMounts:
        - name: spool
          mountPath: /var/spool/halon/queue
        - mountPath: /etc/halon
          name: config
      volumes:
      - name: config
        configMap:
          name: smtpd
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: spool
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: spool
      resources:
        requests:
          storage: 10Gi
  serviceName: smtpd