{{- if .Values.global.policyd.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "policyd.fullname" . }}
  labels:
    {{- include "policyd.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
        storage: {{ .Values.storage }}
{{- end }}