FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="support@halon.io"

ARG HALON_REPO_USER
ARG HALON_REPO_PASS

RUN apt-get update && apt-get install -y wget gnupg
RUN apt-get update && apt-get install -y apt-transport-https

RUN wget -qO - https://raw.githubusercontent.com/halon/pgp-keys/master/pgp-keys/7F0A73B5.asc | apt-key add -
RUN echo "deb https://repo.halon.io/ noble stable" >> /etc/apt/sources.list.d/halon.list
RUN echo "machine repo.halon.io login ${HALON_REPO_USER} password ${HALON_REPO_PASS}" >> /etc/apt/auth.conf
RUN apt-get update && apt-get install -y halon-clusterd=1.0.0

RUN groupadd -g 2000 clusterd
RUN useradd -u 2000 -g 2000 clusterd

CMD ["sh", "-c", "exec env LD_LIBRARY_PATH=/opt/halon/lib/clusterd/:$LD_LIBRARY_PATH /opt/halon/sbin/clusterd -f"]