apiVersion: v1
kind: ConfigMap
metadata:
  name: web
data:
  web.yaml: |-
    version: "1.16"
    listeners:
      - port: 80
    hosts:
      - address: smtpd.default.svc.cluster.local
        port: 80
        expand: true
        processes:
          - smtpd
      - address: rated.default.svc.cluster.local
        port: 80
        expand: true
        processes:
          - rated
    reresolve: 5
    users:
      - username: admin
        password: $2y$12$BzWuHfwX9qDhhomp4Oe/5.7FYwrk1sQfytTeoosv7tqXv/D8hOebO
    environment:
      privdrop:
        user: web
        group: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: web:1.16.0
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          tcpSocket:
            port: 80
        livenessProbe:
          tcpSocket:
            port: 80
        volumeMounts:
        - mountPath: /etc/halon
          name: config
      volumes:
      - name: config
        configMap:
          name: web